/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Wizard = {
  _type: "wizard";
  title?: string;
};

export type Menu = {
  _id: string;
  _type: "menu";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  menuType?: "navbar" | "footer";
  menuItems?: Array<{
    label?: string;
    linkType?: "internal" | "external" | "anchor";
    page?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "page";
    };
    externalUrl?: string;
    anchor?: string;
    openInNewTab?: boolean;
    _type: "link";
    _key: string;
  }>;
  footerColumns?: Array<{
    title?: string;
    links?: Array<{
      label?: string;
      linkType?: "internal" | "external" | "anchor";
      page?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "page";
      };
      externalUrl?: string;
      anchor?: string;
      openInNewTab?: boolean;
      _type: "link";
      _key: string;
    }>;
    _type: "footerColumn";
    _key: string;
  }>;
  footerCopyright?: string;
  footerNote?: string;
};

export type RichText = {
  _type: "richText";
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      openInNewTab?: boolean;
      nofollow?: boolean;
      _type: "link";
      _key: string;
    } | {
      reference?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "page";
      };
      _type: "internalLink";
      _key: string;
    }>;
    level?: number;
    _type: "contentBlock";
    _key: string;
  }>;
};

export type ContentBlock = {
  _type: "contentBlock";
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href?: string;
    openInNewTab?: boolean;
    nofollow?: boolean;
    _type: "link";
    _key: string;
  } | {
    reference?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "page";
    };
    _type: "internalLink";
    _key: string;
  }>;
  level?: number;
};

export type Header = {
  _type: "header";
  title?: string;
  subheadline?: string;
  description?: string;
  backgroundImage?: CloudinaryAsset;
};

export type TickerItem = {
  _type: "tickerItem";
  title?: string;
  description?: string;
  imageCloudinary?: CloudinaryAsset;
};

export type TickerGallery = {
  _type: "tickerGallery";
  name?: string;
  tickerItems?: Array<{
    _key: string;
  } & TickerItem>;
};

export type PageBuilder = Array<{
  _key: string;
} & Header | {
  _key: string;
} & RichText | {
  _key: string;
} & TickerGallery | {
  _key: string;
} & Wizard>;

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  content?: PageBuilder;
  mainImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type CloudinaryAssetContextCustom = {
  _type: "cloudinary.assetContextCustom";
  alt?: string;
  caption?: string;
};

export type CloudinaryAssetDerived = {
  _type: "cloudinary.assetDerived";
  raw_transformation?: string;
  url?: string;
  secure_url?: string;
};

export type CloudinaryAsset = {
  _type: "cloudinary.asset";
  public_id?: string;
  resource_type?: string;
  type?: string;
  format?: string;
  version?: number;
  url?: string;
  secure_url?: string;
  width?: number;
  height?: number;
  bytes?: number;
  duration?: number;
  tags?: Array<string>;
  created_at?: string;
  derived?: Array<{
    _key: string;
  } & CloudinaryAssetDerived>;
  access_mode?: string;
  context?: CloudinaryAssetContext;
};

export type CloudinaryAssetContext = {
  _type: "cloudinary.assetContext";
  custom?: CloudinaryAssetContextCustom;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes = Wizard | Menu | RichText | ContentBlock | Header | TickerItem | TickerGallery | PageBuilder | Page | CloudinaryAssetContextCustom | CloudinaryAssetDerived | CloudinaryAsset | CloudinaryAssetContext | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageHotspot | SanityImageCrop | SanityFileAsset | SanityImageAsset | SanityImageMetadata | Geopoint | Slug | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Helpers to extract array element types
type _ArrayElement<T> = T extends Array<infer U> ? U : never;

// Base shapes from generated types
type _MenuItemBase = _ArrayElement<NonNullable<Menu["menuItems"]>>;
type _FooterColumnBase = _ArrayElement<NonNullable<Menu["footerColumns"]>>;
type _FooterLinkBase = _ArrayElement<NonNullable<NonNullable<_FooterColumnBase>["links"]>>;

/**
 * Navbar link after GROQ projection:
 * We dereference `page->slug.current` into a simple `slug?: string`.
 */
export type NavbarMenuItemProjected = Omit<_MenuItemBase, "page"> & {
  slug?: string;                // e.g. "about"
  // Keep other optional fields from schema:
  label?: string;
  linkType?: "internal" | "external" | "anchor";
  externalUrl?: string;
  anchor?: string;
  openInNewTab?: boolean;
  _key: string;
};

/**
 * Footer link after GROQ projection (same slug projection).
 */
export type FooterLinkProjected = Omit<_FooterLinkBase, "page"> & {
  slug?: string;
  label?: string;
  linkType?: "internal" | "external" | "anchor";
  externalUrl?: string;
  anchor?: string;
  openInNewTab?: boolean;
  _key: string;
};

export type FooterColumnProjected = Omit<_FooterColumnBase, "links"> & {
  links?: FooterLinkProjected[];
};

/**
 * Menu document after projecting slugs on both navbar items and footer links.
 * (Use whichever one you query—navbar or footer.)
 */
export type MenuNavbarProjected = Omit<Menu, "menuItems" | "footerColumns"> & {
  menuType?: "navbar" | "footer";
  menuItems?: NavbarMenuItemProjected[];
};

export type MenuFooterProjected = Omit<Menu, "menuItems" | "footerColumns"> & {
  menuType?: "navbar" | "footer";
  footerColumns?: FooterColumnProjected[];
};

/**
 * Convenience UI types
 */
export type NavbarData = {
  menuItems?: NavbarMenuItemProjected[];
};

export type FooterData = {
  footerColumns?: FooterColumnProjected[];
};