/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Wizard = {
  _type: "wizard";
  title?: string;
};

export type Menu = {
  _id: string;
  _type: "menu";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  menuType?: "navbar" | "footer";
  menuItems?: Array<{
    label?: string;
    linkType?: "internal" | "external" | "anchor";
    page?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "page";
    };
    externalUrl?: string;
    anchor?: string;
    openInNewTab?: boolean;
    _type: "link";
    _key: string;
  }>;
  footerColumns?: Array<{
    title?: string;
    links?: Array<{
      label?: string;
      linkType?: "internal" | "external" | "anchor";
      page?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "page";
      };
      externalUrl?: string;
      anchor?: string;
      openInNewTab?: boolean;
      _type: "link";
      _key: string;
    }>;
    _type: "footerColumn";
    _key: string;
  }>;
  footerCopyright?: string;
  footerNote?: string;
};

export type RichText = {
  _type: "richText";
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      openInNewTab?: boolean;
      nofollow?: boolean;
      _type: "link";
      _key: string;
    } | {
      reference?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "page";
      };
      _type: "internalLink";
      _key: string;
    }>;
    level?: number;
    _type: "contentBlock";
    _key: string;
  }>;
};

export type ContentBlock = {
  _type: "contentBlock";
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href?: string;
    openInNewTab?: boolean;
    nofollow?: boolean;
    _type: "link";
    _key: string;
  } | {
    reference?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "page";
    };
    _type: "internalLink";
    _key: string;
  }>;
  level?: number;
};

export type Header = {
  _type: "header";
  title?: string;
  subheadline?: string;
  description?: string;
  backgroundImage?: CloudinaryAsset;
};
export type Header2 = {
  _type: "header";
  title?: string;
  subheadline?: string;
  description?: string;
  backgroundImage?: CloudinaryAsset;
};

export type TickerItem = {
  _key: string;
  _type: "tickerItem";
  title?: string;
  description?: string;
  imageCloudinary?: CloudinaryAsset;
};
export type TickersliderItemContent = {
  _type: "tickersliderItemContent";
  title?: string;
  description?: string;
  imageCloudinary?: CloudinaryAsset;
};

export type TickerContentGallery = {
  _type: "tickerContentGallery";
  name?: string;
  tickerItems?: Array<{
    _key: string;
  } & TickerItem>;
};
export type TickerGallery = {
  _type: "tickerGallery";
  name?: string;
  tickersliderItemContents?: Array<{
    _key: string;
  } & TickerItem>;
};

export type PageBuilder = Array<
  ({ _key: string } & Header) |
  ({ _key: string } & RichText) |
  ({ _key: string } & TickerGallery) |
  ({ _key: string } & HeroSection) |
  ({ _key: string } & MediaHeroSectionProps) |
  ({ _key: string } & TextHeadlineCombo) |
  ({ _key: string } & MediaScrollHighlightSection) |
  ({ _key: string } & ExpandableCards) |
  ({ _key: string } & Wizard)
>;


export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  content?: PageBuilder;
  mainImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type CloudinaryAssetContextCustom = {
  _type: "cloudinary.assetContextCustom";
  alt?: string;
  caption?: string;
};

export type CloudinaryAssetDerived = {
  _type: "cloudinary.assetDerived";
  raw_transformation?: string;
  url?: string;
  secure_url?: string;
};

export type CloudinaryAsset = {
  _type: "cloudinary.asset";
  public_id?: string;
  resource_type?: string;
  type?: string;
  format?: string;
  version?: number;
  url?: string;
  secure_url?: string;
  width?: number;
  height?: number;
  bytes?: number;
  duration?: number;
  tags?: Array<string>;
  created_at?: string;
  derived?: Array<{
    _key: string;
  } & CloudinaryAssetDerived>;
  access_mode?: string;
  context?: CloudinaryAssetContext;
};

export type CloudinaryAssetContext = {
  _type: "cloudinary.assetContext";
  custom?: CloudinaryAssetContextCustom;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes =
  | Wizard
  | Menu
  | RichText
  | ContentBlock
  | Header
  | Header2
  | TickerItem
  | TickerGallery
  | TickerContentGallery
  | PageBuilder
  | Page
  | CloudinaryAssetContextCustom
  | CloudinaryAssetDerived
  | CloudinaryAsset
  | CloudinaryAssetContext
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityImageAsset
  | SanityImageMetadata
  | Geopoint
  | Slug
  | SanityAssetSourceData
  | CtaLink
  | Cta
  | ExpandableCardItem
  | ExpandableCards;

export declare const internalGroqTypeReferenceTo: unique symbol;
// Helpers to extract array element types
type _ArrayElement<T> = T extends Array<infer U> ? U : never;

// Base shapes from generated types
type _MenuItemBase = _ArrayElement<NonNullable<Menu["menuItems"]>>;
type _FooterColumnBase = _ArrayElement<NonNullable<Menu["footerColumns"]>>;
type _FooterLinkBase = _ArrayElement<NonNullable<NonNullable<_FooterColumnBase>["links"]>>;

/**
 * Navbar link after GROQ projection:
 * We dereference `page->slug.current` into a simple `slug?: string`.
 */
export type NavbarMenuItemProjected = Omit<_MenuItemBase, "page"> & {
  slug?: string;                // e.g. "about"
  // Keep other optional fields from schema:
  label?: string;
  linkType?: "internal" | "external" | "anchor";
  externalUrl?: string;
  anchor?: string;
  openInNewTab?: boolean;
  _key: string;
};

/**
 * Footer link after GROQ projection (same slug projection).
 */
export type FooterLinkProjected = Omit<_FooterLinkBase, "page"> & {
  slug?: string;
  label?: string;
  linkType?: "internal" | "external" | "anchor";
  externalUrl?: string;
  anchor?: string;
  openInNewTab?: boolean;
  _key: string;
};

export type FooterColumnProjected = Omit<_FooterColumnBase, "links"> & {
  links?: FooterLinkProjected[];
};

/**
 * Menu document after projecting slugs on both navbar items and footer links.
 * (Use whichever one you query—navbar or footer.)
 */
export type MenuNavbarProjected = Omit<Menu, "menuItems" | "footerColumns"> & {
  menuType?: "navbar" | "footer";
  menuItems?: NavbarMenuItemProjected[];
};

export type MenuFooterProjected = Omit<Menu, "menuItems" | "footerColumns"> & {
  menuType?: "navbar" | "footer";
  footerColumns?: FooterColumnProjected[];
};

/**
 * Convenience UI types
 */
export type NavbarData = {
  menuItems?: NavbarMenuItemProjected[];
};

export type FooterData = {
  footerColumns?: FooterColumnProjected[];
};
export type HeroSection = {
  _type: "heroSection";
  _key?: string;
  title?: string;
  subheadline?: string;
  description?: string;
  backgroundImage?: CloudinaryAsset;
  logoImageUrl?: CloudinaryAsset;
  backgroundAlt?: string;
};
export type HeroSectionProjected = {
  _type: "heroSection";
  _key?: string;

  title?: string;
  subheadline?: string;
  description?: string;
  backgroundAlt?: string;

  backgroundImageUrl?: string;
  logoImage?: string;
};
export type MediaHeroSectionProps = {
  _type: "mediaHeroSection";
  id?: string;
  className?: string;

  heading?: string;
  subheading?: string;

  useVideo?: boolean;
  imageSrc?: string;
  videoSrc?: string;
  imageAlt?: string;
  enableParallax?: boolean;
  overlayOpacity?: number;

  animation?: {
    delay?: number;
    staggerDelay?: number;
    duration?: number;
    distance?: number;
  };
};

// Reusable enums for style (kept narrow to what the schema allows)
export type THCAlign = "left" | "center" | "right";
export type THCSize = "xl" | "lg" | "md" | "sm";
export type THCSpacing = "tight" | "normal" | "loose";

/**
 * textHeadlineCombo — raw shape from Sanity (matches your schema)
 */
export type TextHeadlineCombo = {
  _type: "textHeadlineCombo";
  _key?: string;

  eyebrow?: string;
  headline?: string;   // required in schema, optional in TS for runtime safety
  highlight?: string;
  subhead?: string;

  style?: {
    align?: THCAlign;       // default "left"
    size?: THCSize;         // default "xl"
    animate?: boolean;      // default true
    spacing?: THCSpacing;   // default "normal"
  };
};

/**
 * Optional projected shape if you flatten style.* in GROQ
 * (only add/use this if your GROQ returns flattened fields)
 */
export type TextHeadlineComboProjected = {
  _type: "textHeadlineCombo";
  _key?: string;

  eyebrow?: string;
  headline?: string;
  highlight?: string;
  subhead?: string;

  // Flattened style
  align?: THCAlign;
  size?: THCSize;
  animate?: boolean;
  spacing?: THCSpacing;
};

export type ScrollHighlightItem = {
  name?: string;
  text?: string;
};

export type MediaScrollHighlightSection = {
  _type: "mediaScrollHighlightSection";
  _key?: string;

  useVideo?: boolean;
  imageSrc?: string;   // projected
  videoSrc?: string;   // projected
  imageAlt?: string;
  enableParallax?: boolean;
  overlayOpacity?: number;

  items?: ScrollHighlightItem[];

  viewportMargin?: string;
  padTopBottomVh?: number;
  padY?: "sm" | "md" | "lg";
};

// Reusable CTA link for buttons (internal page OR external URL)
export type CtaLink = {
  _type: "ctaLink";
  linkType?: "internal" | "external";
  page?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "page";
  };
  externalUrl?: string;
};

// CTA object: text + link
export type Cta = {
  _type: "cta";
  text?: string;
  link?: CtaLink;
};

// Single card (raw, as stored in Sanity)
export type ExpandableCardItem = {
  _type: "expandableCardItem";
  _key: string;
  title?: string;
  description?: string;
  image?: CloudinaryAsset;
  imageAlt?: string;
  logo?: CloudinaryAsset;
  ctaButton?: Cta;
  body?: Array<{ _key: string } & ContentBlock>; // Portable Text blocks
};

// Section (raw, as stored in Sanity)
export type ExpandableCards = {
  _type: "expandableCards";
  _key?: string;
  items?: Array<{ _key: string } & ExpandableCardItem>;
};


// One card after GROQ projection (what your component expects)
export type ExpandableCardItemProjected = {
  _key?: string;
  title: string;
  description?: string;
  imageSrc: string;   // image.secure_url
  imageAlt?: string;  // coalesce(image.context.custom.alt, imageAlt)
  logoSrc?: string;   // logo.secure_url
  body?: any[];       // Portable Text (projected as-is)
  ctaText?: string;   // ctaButton.text
  ctaHref?: string;   // resolved from ctaButton.link (internal/external)
};

// Section after GROQ projection
export type ExpandableCardsProjected = {
  _type: "expandableCards";
  _key?: string;
  items?: ExpandableCardItemProjected[];
};